### ISSUE TITLE
CLI route to remove or create the file

### ISSUE THREAD

**Issue by stijnhau** [juliangut/zf-maintenance#2]
Is it possible to add a route to create the 'Jgut\Zf\Maintenance\Provider\FileProvider' 'file' with executing some code in CLI (so i can disable the site betwen some hours by crontab and so on.

**Comment by juliangut** [comment]
I've thought this through and I see no point on creating a CLI route to create/delete a file when you can just have a cronjob to create/delete the file on specific times (just `touch` and `rm`)

The solely purpose of `Jgut\Zf\Maintenance\Provider\FileProvider` is to verify if a certain file exists or not, if it exists then maintenance mode is considered on, the way that file is managed is up to you and your system (crontab, manually, ftp ...)

I'm working on a `Jgut\Zf\Maintenance\Provider\CronProvider` extending `Jgut\Zf\Maintenance\Provider\ScheduledProviderInterface` for v2.0 (issue #1) to define scheduled maintenance periods with cron syntax
It will be sort of a middle solution because I think it is better to actually use a cronjob to create/delete a file or set/delete an environment variable for `EnvironmentProvider`

**Comment by juliangut** [comment]
I've just pushed `CrontabProvider`into branch v2.0 that handles CRON syntax and `\DateInterval` to define scheduled maintenance periods
Again, I see no point on having a CLI controller  to create files
